version: '3.8'
services:
  node0:
    build: .
    container_name: lygus-node0
    hostname: node0
    command: ["-n", "0", "-p", "/data/peers.txt", "-d", "/data", "-l", "8080", "-s", "10000", "-v"]
    ports:
      - "8080:8080"
    volumes:
      - node0-data:/data
      - ./peers.txt:/data/peers.txt:ro
    networks:
      lygus-net:
        ipv4_address: 172.20.0.10
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    sysctls:
      - net.ipv4.ip_forward=1

  node1:
    build: .
    container_name: lygus-node1
    hostname: node1
    command: ["-n", "1", "-p", "/data/peers.txt", "-d", "/data", "-l", "8080", "-s", "10000", "-v"]
    ports:
      - "8081:8080"
    volumes:
      - node1-data:/data
      - ./peers.txt:/data/peers.txt:ro
    networks:
      lygus-net:
        ipv4_address: 172.20.0.11
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    sysctls:
      - net.ipv4.ip_forward=1

  node2:
    build: .
    container_name: lygus-node2
    hostname: node2
    command: ["-n", "2", "-p", "/data/peers.txt", "-d", "/data", "-l", "8080", "-s", "10000", "-v"]
    ports:
      - "8082:8080"
    volumes:
      - node2-data:/data
      - ./peers.txt:/data/peers.txt:ro
    networks:
      lygus-net:
        ipv4_address: 172.20.0.12
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    sysctls:
      - net.ipv4.ip_forward=1

  node3:
    build: .
    container_name: lygus-node3
    hostname: node3
    command: ["-n", "3", "-p", "/data/peers.txt", "-d", "/data", "-l", "8080", "-s", "10000", "-v"]
    ports:
      - "8083:8080"
    volumes:
      - node3-data:/data
      - ./peers.txt:/data/peers.txt:ro
    networks:
      lygus-net:
        ipv4_address: 172.20.0.13
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    sysctls:
      - net.ipv4.ip_forward=1

  node4:
    build: .
    container_name: lygus-node4
    hostname: node4
    command: ["-n", "4", "-p", "/data/peers.txt", "-d", "/data", "-l", "8080", "-s", "10000", "-v"]
    ports:
      - "8084:8080"
    volumes:
      - node4-data:/data
      - ./peers.txt:/data/peers.txt:ro
    networks:
      lygus-net:
        ipv4_address: 172.20.0.14
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    sysctls:
      - net.ipv4.ip_forward=1

volumes:
  node0-data:
  node1-data:
  node2-data:
  node3-data:
  node4-data:

networks:
  lygus-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
